Repository owncloud/files_external_s3, pull requests merged in 2020-04, with the labels that each got.

#386 Update symfony/polyfill-mbstring (v1.14.0 => v1.15.0) and aws-sdk-php
  composer.lock
Labels: 3 - To Review, dependencies

#387 [Tests-Only] Update phpstan to latest version
  .drone.star
  lib/AppInfo/Application.php
  lib/Storage/AmazonS3.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#389 [Tests-Only] Bump phan 2.7
  .drone.star
  appinfo/Migrations/Version20190905111710.php
  lib/AppInfo/Application.php
  lib/Storage/AmazonS3.php
  vendor-bin/phan/composer.json
Labels: 4 - To release, QA-team

#400 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To Review, QA-team
